FROM node:12-alpine AS build
ARG ENV_TYPE
ENV ENV_TYPE=${ENV_TYPE}
RUN mkdir /app
WORKDIR /app
#RUN apk add --update python make g++\
#   && rm -rf /var/cache/apk/*
COPY package.json ./
COPY . .
RUN apk add --no-cache git
RUN git --version
RUN npm i --legacy-peer-deps
#--global node-gyp
RUN npm run node:build:${ENV_TYPE}
#RUN npm run build --configuration=${ENV_TYPE}
#RUN node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --configuration=qa
FROM nginx:alpine
COPY --from=build /app/dist/ /var/www/
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/ /usr/share/nginx/html
RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log